# permissions for end users to edit loadtestmanagers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: loadtestmanager-editor-role
rules:
- apiGroups:
  - maca.itohdak.github.com
  resources:
  - loadtestmanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - maca.itohdak.github.com
  resources:
  - loadtestmanagers/status
  verbs:
  - get
